export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const LOAD_RIDES_SUCCESS = 'LOAD_RIDES_SUCCESS';
export const UPDATE_RIDE_SUCCESS = 'UPDATE_RIDE_SUCCESS';
export const CREATE_RIDE_SUCCESS = 'CREATE_RIDE_SUCCESS';
export const DELETE_RIDE_SUCCESS = 'DELETE_RIDE_SUCCESS';

export const LOAD_RIDES_FAILURE = 'LOAD_RIDES_FAILURE';
export const UPDATE_RIDE_FAILURE = 'UPDATE_RIDE_FAILURE';
export const CREATE_RIDE_FAILURE = 'CREATE_RIDE_FAILURE';
export const DELETE_RIDE_FAILURE = 'DELETE_RIDE_FAILURE';
