export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const LOAD_RIDES_REQUEST = 'LOAD_RIDES_REQUEST';
export const LOAD_RIDES_SUCCESS = 'LOAD_RIDES_SUCCESS';
export const LOAD_RIDES_FAILURE = 'LOAD_RIDES_FAILURE';

export const CREATE_RIDE_REQUEST = 'CREATE_RIDE_REQUEST';
export const CREATE_RIDE_SUCCESS = 'CREATE_RIDE_SUCCESS';
export const CREATE_RIDE_FAILURE = 'CREATE_RIDE_FAILURE';

export const UPDATE_RIDE_REQUEST = 'UPDATE_RIDE_REQUEST';
export const UPDATE_RIDE_SUCCESS = 'UPDATE_RIDE_SUCCESS';
export const UPDATE_RIDE_FAILURE = 'UPDATE_RIDE_FAILURE';

export const DELETE_RIDE_REQUEST = 'DELETE_RIDE_REQUEST';
export const DELETE_RIDE_SUCCESS = 'DELETE_RIDE_SUCCESS';
export const DELETE_RIDE_FAILURE = 'DELETE_RIDE_FAILURE';
